spring.application.name=coach

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=local

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS / App
app.s3.bucket=${S3_BUCKET}
app.sqs.queue-url=${SQS_QUEUE_URL}
app.worker.secret=${WORKER_SECRET}
app.front.base-url=${FRONT_BASE_URL}
app.backend.base-url=${BACKEND_BASE_URL}